from __future__ import division
import math

import RPi

# Gantry constants
MACHINE_LENGTH = 1000
MACHINE_HEIGHT = 500

# Software limits
TABLE_MIN_POS = 0
TABLE_MAX_POS = 250

RODCARR_X_MIN_POS = 0
RODCARR_X_MAX_POS = 795

RODCARR_Y_MIN_POS = 0
RODCARR_Y_MAX_POS = 790

TAPECARR_X_LEFT_MIN_POS = 0
TAPECARR_X_LEFT_MAX_POS = 350

TAPECARR_X_RIGHT_MIN_POS = 0
TAPECARR_X_RIGHT_MAX_POS = 330

TAPECARR_Y_MIN_POS = 0
TAPECARR_Y_MAX_POS = 775

TAPE_MIN_POS = 0
TAPE_MAX_POS = 700

TAPE_CAM_MIN_POS = 0
TAPE_CAM_MAX_POS = 35

# PWM chip constants
PWM_PULSE_LENGTH = 4095
DEFAULT_PWM_FREQ = 60

# Component enable or disable constants
ENABLED = 1
DISABLED = 0

# Motor configuration constants
STEPPER_ENABLE = RPi.GPIO.HIGH
STEPPER_DISABLE = RPi.GPIO.LOW
STEPPER_ROT_CW = RPi.GPIO.LOW
STEPPER_ROT_CCW = RPi.GPIO.HIGH
STEPPER_PWM_TIME_MODIFIER = 0.925
STEPPER_MAX_RPM = 300

DC_MAX_RPM = 100
DC_ROT_CW = RPi.GPIO.LOW
DC_ROT_CCW = RPi.GPIO.HIGH

SERVO_MIN_ROT = 0
SERVO_MAX_ROT = 180
TAPE_X_LEFT_SERVO_MIN_PULSE = 340
TAPE_X_LEFT_SERVO_MAX_PULSE = 560
TAPE_X_RIGHT_SERVO_MIN_PULSE = 135
TAPE_X_RIGHT_SERVO_MAX_PULSE = 360
TAPE_Y_SERVO_MIN_PULSE = 285
TAPE_Y_SERVO_MAX_PULSE = 580
SERVO_PWM_FREQ = 60
SERVO_TRANS_TIME = 1

# Stepper motor component configurations
TABLE_STEPS_PER_MM = 25
TABLE_STEPS_PER_REV = 200
TABLE_MM_PER_REV = TABLE_STEPS_PER_REV / TABLE_STEPS_PER_MM

CARR_CIRCUMFERENCE = 60
CARR_STEPS_PER_REV = 400
CARR_STEPS_PER_MM = CARR_STEPS_PER_REV / CARR_CIRCUMFERENCE
CARR_MM_PER_REV = CARR_STEPS_PER_REV / CARR_STEPS_PER_MM

TAPE_DIAMETER = 43
TAPE_CIRCUMFERENCE = TAPE_DIAMETER * math.pi
TAPE_STEPS_PER_REV = 200
TAPE_STEPS_PER_MM = TAPE_STEPS_PER_REV / TAPE_CIRCUMFERENCE
TAPE_MM_PER_REV = TAPE_STEPS_PER_REV / TAPE_STEPS_PER_MM
TAPE_RET_EXTRA_MM = 20

# Homing configuration
HOME_DIR_POS = 1
HOME_DIR_NEG = -1

TABLE_HOME_DIR = HOME_DIR_POS
TABLE_HOME_OFFSET = 5
TABLE_HOME_RPM = 225

ROD_X_AXIS_HOME_DIR = HOME_DIR_POS
ROD_Y_AXIS_HOME_DIR = HOME_DIR_NEG
ROD_HOME_OFFSET = 5
ROD_HOME_RPM = 100

TAPE_X_AXIS_LEFT_HOME_DIR = HOME_DIR_POS
TAPE_X_AXIS_RIGHT_HOME_DIR = HOME_DIR_NEG
TAPE_Y_AXIS_HOME_DIR = HOME_DIR_POS
TAPE_HOME_OFFSET = 5
TAPE_HOME_RPM = 100

TAPE_HOME_DIR = HOME_DIR_POS

# Push button configuration
PUSH_BUTTON_RELEASED = RPi.GPIO.HIGH
PUSH_BUTTON_PRESSED = RPi.GPIO.LOW

# Limit switch configuration
LIMIT_SWITCH_OPEN = RPi.GPIO.HIGH
LIMIT_SWITCH_CLOSE = RPi.GPIO.LOW
