from __future__ import division

# Gantry constants
MACHINE_LENGTH = 1000
MACHINE_HEIGHT = 500

# PWM chip constants
PWM_PULSE_LENGTH = 4095
DEFAULT_PWM_FREQ = 60

# Motor configuration constants
STEPPER_ENABLE = 1
STEPPER_DISABLE = 0
DC_MAX_RPM = 100
SERVO_MIN_ROT = 0
SERVO_MAX_ROT = 180
SERVO_MIN_PULSE = 153
SERVO_MAX_PULSE = 640
SERVO_PWM_FREQ = 60
SERVO_TRANS_TIME = 1

ROT_CW = 1
ROT_CCW = 0

TABLE_STEPS_PER_MM = 25
TABLE_STEPS_PER_REV = 200
TABLE_MM_PER_REV = TABLE_STEPS_PER_REV / TABLE_STEPS_PER_MM

CARR_STEPS_PER_MM = 3.33
CARR_STEPS_PER_REV = 200
CARR_MM_PER_REV = CARR_STEPS_PER_REV / CARR_STEPS_PER_MM

TAPE_STEPS_PER_MM = 3.33
TAPE_STEPS_PER_REV = 200
TAPE_MM_PER_REV = TAPE_STEPS_PER_REV / TAPE_STEPS_PER_MM

TAPE_CAM_LENGTH = 30

# Home direction
HOME_DIR_POS = 1
HOME_DIR_NEG = -1

ROD_X_AXIS_HOME = HOME_DIR_POS
ROD_Y_AXIS_HOME = HOME_DIR_POS

TAPE_X_AXIS_LEFT_HOME = HOME_DIR_POS
TAPE_X_AXIS_RIGHT_HOME = HOME_DIR_POS
TAPE_Y_AXIS_HOME = HOME_DIR_POS
